//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quản_lý_điểm_sinh_vien_CNTT {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class frmMain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal frmMain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quản_lý_điểm_sinh_vien_CNTT.frmMain", typeof(frmMain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=131, Height=22}.
        /// </summary>
        public static System.Drawing.Size aboutToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("aboutToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About ... ....
        /// </summary>
        public static string aboutToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("aboutToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btl1_Image {
            get {
                object obj = ResourceManager.GetObject("btl1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=143}.
        /// </summary>
        public static System.Drawing.Point btl1_Location {
            get {
                object obj = ResourceManager.GetObject("btl1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=57}.
        /// </summary>
        public static System.Drawing.Size btl1_Size {
            get {
                object obj = ResourceManager.GetObject("btl1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        public static int btl1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btl1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QLSinh Viên.
        /// </summary>
        public static string btl1_Text {
            get {
                return ResourceManager.GetString("btl1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btl2_Image {
            get {
                object obj = ResourceManager.GetObject("btl2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=206}.
        /// </summary>
        public static System.Drawing.Point btl2_Location {
            get {
                object obj = ResourceManager.GetObject("btl2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=57}.
        /// </summary>
        public static System.Drawing.Size btl2_Size {
            get {
                object obj = ResourceManager.GetObject("btl2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int btl2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btl2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QL Giảng Viên.
        /// </summary>
        public static string btl2_Text {
            get {
                return ResourceManager.GetString("btl2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btl3_Image {
            get {
                object obj = ResourceManager.GetObject("btl3.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=269}.
        /// </summary>
        public static System.Drawing.Point btl3_Location {
            get {
                object obj = ResourceManager.GetObject("btl3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=57}.
        /// </summary>
        public static System.Drawing.Size btl3_Size {
            get {
                object obj = ResourceManager.GetObject("btl3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        public static int btl3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btl3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý điểm Sinh viên.
        /// </summary>
        public static string btl3_Text {
            get {
                return ResourceManager.GetString("btl3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btl4_Image {
            get {
                object obj = ResourceManager.GetObject("btl4.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=332}.
        /// </summary>
        public static System.Drawing.Point btl4_Location {
            get {
                object obj = ResourceManager.GetObject("btl4.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=57}.
        /// </summary>
        public static System.Drawing.Size btl4_Size {
            get {
                object obj = ResourceManager.GetObject("btl4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        public static int btl4_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btl4.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Khoa.
        /// </summary>
        public static string btl4_Text {
            get {
                return ResourceManager.GetString("btl4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btl5_Image {
            get {
                object obj = ResourceManager.GetObject("btl5.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=395}.
        /// </summary>
        public static System.Drawing.Point btl5_Location {
            get {
                object obj = ResourceManager.GetObject("btl5.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=57}.
        /// </summary>
        public static System.Drawing.Size btl5_Size {
            get {
                object obj = ResourceManager.GetObject("btl5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        public static int btl5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btl5.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Lớp.
        /// </summary>
        public static string btl5_Text {
            get {
                return ResourceManager.GetString("btl5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap btl6_Image {
            get {
                object obj = ResourceManager.GetObject("btl6.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=5,Y=458}.
        /// </summary>
        public static System.Drawing.Point btl6_Location {
            get {
                object obj = ResourceManager.GetObject("btl6.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=97, Height=57}.
        /// </summary>
        public static System.Drawing.Size btl6_Size {
            get {
                object obj = ResourceManager.GetObject("btl6.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        public static int btl6_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btl6.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lý Môn học.
        /// </summary>
        public static string btl6_Text {
            get {
                return ResourceManager.GetString("btl6.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=62, Height=20}.
        /// </summary>
        public static System.Drawing.Size helpMenu_Size {
            get {
                object obj = ResourceManager.GetObject("helpMenu.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trợ giúp.
        /// </summary>
        public static string helpMenu_Text {
            get {
                return ResourceManager.GetString("helpMenu.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=126, Height=22}.
        /// </summary>
        public static System.Drawing.Size menuBarToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("menuBarToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Bar.
        /// </summary>
        public static string menuBarToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("menuBarToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=0}.
        /// </summary>
        public static System.Drawing.Point menuStrip_Location {
            get {
                object obj = ResourceManager.GetObject("menuStrip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1008, Height=24}.
        /// </summary>
        public static System.Drawing.Size menuStrip_Size {
            get {
                object obj = ResourceManager.GetObject("menuStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        public static int menuStrip_TabIndex {
            get {
                object obj = ResourceManager.GetObject("menuStrip.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuStrip.
        /// </summary>
        public static string menuStrip_Text {
            get {
                return ResourceManager.GetString("menuStrip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=215,Y=3}.
        /// </summary>
        public static System.Drawing.Point menuStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("menuStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDiem_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDiem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm môn học.
        /// </summary>
        public static string mnuDiem_Text {
            get {
                return ResourceManager.GetString("mnuDiem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=187, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDiemTK_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDiemTK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điểm tổng kết của SV.
        /// </summary>
        public static string mnuDiemTK_Text {
            get {
                return ResourceManager.GetString("mnuDiemTK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Black].
        /// </summary>
        public static System.Drawing.Color mnuDN_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("mnuDN.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDN_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDN.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng nhập.
        /// </summary>
        public static string mnuDN_Text {
            get {
                return ResourceManager.GetString("mnuDN.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDoiMK_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDoiMK.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đổi mật khẩu.
        /// </summary>
        public static string mnuDoiMK_Text {
            get {
                return ResourceManager.GetString("mnuDoiMK.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=187, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDSSV_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDSSV.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách SV.
        /// </summary>
        public static string mnuDSSV_Text {
            get {
                return ResourceManager.GetString("mnuDSSV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDSTL_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDSTL.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách SV thi lại.
        /// </summary>
        public static string mnuDSTL_Text {
            get {
                return ResourceManager.GetString("mnuDSTL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [Black].
        /// </summary>
        public static System.Drawing.Color mnuDX_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("mnuDX.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuDX_Size {
            get {
                object obj = ResourceManager.GetObject("mnuDX.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đăng xuất.
        /// </summary>
        public static string mnuDX_Text {
            get {
                return ResourceManager.GetString("mnuDX.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuExit_Size {
            get {
                object obj = ResourceManager.GetObject("mnuExit.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        public static string mnuExit_Text {
            get {
                return ResourceManager.GetString("mnuExit.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuGV_Size {
            get {
                object obj = ResourceManager.GetObject("mnuGV.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giảng viên.
        /// </summary>
        public static string mnuGV_Text {
            get {
                return ResourceManager.GetString("mnuGV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuHL_Size {
            get {
                object obj = ResourceManager.GetObject("mnuHL.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Học lại.
        /// </summary>
        public static string mnuHL_Text {
            get {
                return ResourceManager.GetString("mnuHL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=74, Height=20}.
        /// </summary>
        public static System.Drawing.Size MnuItemDanhMuc_Size {
            get {
                object obj = ResourceManager.GetObject("MnuItemDanhMuc.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh mục.
        /// </summary>
        public static string MnuItemDanhMuc_Text {
            get {
                return ResourceManager.GetString("MnuItemDanhMuc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Color similar to Color [ActiveBorder].
        /// </summary>
        public static System.Drawing.Color mnuItemHethong_ImageTransparentColor {
            get {
                object obj = ResourceManager.GetObject("mnuItemHethong.ImageTransparentColor", resourceCulture);
                return ((System.Drawing.Color)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=69, Height=20}.
        /// </summary>
        public static System.Drawing.Size mnuItemHethong_Size {
            get {
                object obj = ResourceManager.GetObject("mnuItemHethong.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Hệ thống.
        /// </summary>
        public static string mnuItemHethong_Text {
            get {
                return ResourceManager.GetString("mnuItemHethong.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=60, Height=20}.
        /// </summary>
        public static System.Drawing.Size mnuItemQuanli_Size {
            get {
                object obj = ResourceManager.GetObject("mnuItemQuanli.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí .
        /// </summary>
        public static string mnuItemQuanli_Text {
            get {
                return ResourceManager.GetString("mnuItemQuanli.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=71, Height=20}.
        /// </summary>
        public static System.Drawing.Size mnuItemThongKe_Size {
            get {
                object obj = ResourceManager.GetObject("mnuItemThongKe.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thống kê .
        /// </summary>
        public static string mnuItemThongKe_Text {
            get {
                return ResourceManager.GetString("mnuItemThongKe.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=68, Height=20}.
        /// </summary>
        public static System.Drawing.Size mnuItemtimkiem_Size {
            get {
                object obj = ResourceManager.GetObject("mnuItemtimkiem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tìm kiếm.
        /// </summary>
        public static string mnuItemtimkiem_Text {
            get {
                return ResourceManager.GetString("mnuItemtimkiem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=122, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuKhoa_Size {
            get {
                object obj = ResourceManager.GetObject("mnuKhoa.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khoa.
        /// </summary>
        public static string mnuKhoa_Text {
            get {
                return ResourceManager.GetString("mnuKhoa.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=122, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuLop_Size {
            get {
                object obj = ResourceManager.GetObject("mnuLop.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lớp.
        /// </summary>
        public static string mnuLop_Text {
            get {
                return ResourceManager.GetString("mnuLop.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=122, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuMon_Size {
            get {
                object obj = ResourceManager.GetObject("mnuMon.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Môn học.
        /// </summary>
        public static string mnuMon_Text {
            get {
                return ResourceManager.GetString("mnuMon.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuQuanlinguoidung_Size {
            get {
                object obj = ResourceManager.GetObject("mnuQuanlinguoidung.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quản lí người dùng.
        /// </summary>
        public static string mnuQuanlinguoidung_Text {
            get {
                return ResourceManager.GetString("mnuQuanlinguoidung.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuSV_Size {
            get {
                object obj = ResourceManager.GetObject("mnuSV.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinh viên.
        /// </summary>
        public static string mnuSV_Text {
            get {
                return ResourceManager.GetString("mnuSV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=163, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuThongtinSV_Size {
            get {
                object obj = ResourceManager.GetObject("mnuThongtinSV.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông tin của SV.
        /// </summary>
        public static string mnuThongtinSV_Text {
            get {
                return ResourceManager.GetString("mnuThongtinSV.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=177, Height=22}.
        /// </summary>
        public static System.Drawing.Size mnuTL_Size {
            get {
                object obj = ResourceManager.GetObject("mnuTL.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thi lại.
        /// </summary>
        public static string mnuTL_Text {
            get {
                return ResourceManager.GetString("mnuTL.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=68, Height=20}.
        /// </summary>
        public static System.Drawing.Size mnuWindows_Size {
            get {
                object obj = ResourceManager.GetObject("mnuWindows.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string mnuWindows_Text {
            get {
                return ResourceManager.GetString("mnuWindows.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Top.
        /// </summary>
        public static System.Windows.Forms.DockStyle pictureBox1_Dock {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=24}.
        /// </summary>
        public static System.Drawing.Point pictureBox1_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1008, Height=95}.
        /// </summary>
        public static System.Drawing.Size pictureBox1_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 15.
        /// </summary>
        public static int pictureBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.ImageLayout similar to None.
        /// </summary>
        public static System.Windows.Forms.ImageLayout pictureBox2_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.BackgroundImageLayout", resourceCulture);
                return ((System.Windows.Forms.ImageLayout)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Windows.Forms.DockStyle similar to Left.
        /// </summary>
        public static System.Windows.Forms.DockStyle pictureBox2_Dock {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Dock", resourceCulture);
                return ((System.Windows.Forms.DockStyle)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=119}.
        /// </summary>
        public static System.Drawing.Point pictureBox2_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=103, Height=462}.
        /// </summary>
        public static System.Drawing.Size pictureBox2_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 16.
        /// </summary>
        public static int pictureBox2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=85,Y=125}.
        /// </summary>
        public static System.Drawing.Point pictureBox3_Location {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=17, Height=14}.
        /// </summary>
        public static System.Drawing.Size pictureBox3_Size {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 25.
        /// </summary>
        public static int pictureBox3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("pictureBox3.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=126, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusBarToolStripMenuItem_Size {
            get {
                object obj = ResourceManager.GetObject("statusBarToolStripMenuItem.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Status Bar.
        /// </summary>
        public static string statusBarToolStripMenuItem_Text {
            get {
                return ResourceManager.GetString("statusBarToolStripMenuItem.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=0,Y=581}.
        /// </summary>
        public static System.Drawing.Point statusStrip_Location {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Location", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=1008, Height=22}.
        /// </summary>
        public static System.Drawing.Size statusStrip_Size {
            get {
                object obj = ResourceManager.GetObject("statusStrip.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        public static int statusStrip_TabIndex {
            get {
                object obj = ResourceManager.GetObject("statusStrip.TabIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StatusStrip.
        /// </summary>
        public static string statusStrip_Text {
            get {
                return ResourceManager.GetString("statusStrip.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=16,Y=0}.
        /// </summary>
        public static System.Drawing.Point statusStrip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("statusStrip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=174, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator3_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator3.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=174, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator4_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator4.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=174, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator5_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator5.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=128, Height=6}.
        /// </summary>
        public static System.Drawing.Size toolStripSeparator8_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripSeparator8.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=39, Height=17}.
        /// </summary>
        public static System.Drawing.Size toolStripStatusLabel_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripStatusLabel.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string toolStripStatusLabel_Text {
            get {
                return ResourceManager.GetString("toolStripStatusLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Point similar to {X=124,Y=-1}.
        /// </summary>
        public static System.Drawing.Point toolTip_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
    }
}
